# Generated by Django 4.1 on 2024-09-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0009_alter_comment_comment_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
