# Generated by Django 4.1 on 2024-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0002_blogdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[{1, 'Male'}, {2, 'Female'}, {3, 'Non binary'}], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
