# Generated by Django 4.1 on 2024-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0003_alter_biodata_gender_alter_blogdata_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Non binary')], default=1, max_length=10),
        ),
    ]
