# Generated by Django 4.1 on 2024-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0004_alter_biodata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non binary')], default='M', max_length=10),
        ),
    ]
