# Generated by Django 4.1 on 2024-07-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelloApp', '0005_alter_biodata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HelloApp.biodata')),
            ],
        ),
    ]
